#!/usr/bin/env bash
# generate-watched-dirs-mounts.sh
# Generates deploy/compose/docker-compose.watched-dirs.yml — read-only bind
# mounts of host directories into the monitor container at /host-watch/<name>,
# so WatchedDirSizeCollector can measure their recursive size.
#
# Watched paths come from (first non-empty wins):
#   1. positional args:  scripts/generate-watched-dirs-mounts.sh /var /tmp
#   2. WATCHED_DIRS env var (space-separated): WATCHED_DIRS="/var /tmp" scripts/...
#   3. default: /tmp /var  (matches WatchedDirSizeCollectorConfig baked default)
#
# All paths are validated by homelab_monitor.kernel.watched_dirs (collision
# rules); any collision ABORTS without writing the override.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MONITOR_DIR="${REPO_ROOT}/apps/monitor"

OUT="${OUT_WATCHED_DIRS:-${REPO_ROOT}/deploy/compose/docker-compose.watched-dirs.yml}"

# Resolve watched paths.
if [[ $# -gt 0 ]]; then
  PATHS=("$@")
elif [[ -n "${WATCHED_DIRS:-}" ]]; then
  # shellcheck disable=SC2206
  PATHS=(${WATCHED_DIRS})
else
  PATHS=(/tmp /var)
fi

# Validate + render mount lines via the Python validator.
# Run through uv from the monitor app dir so the package is importable.
# Capture into a var first so the validator's non-zero exit is observed —
# process substitution `< <(...)` hides the exit code from set -e / pipefail.
if ! VALIDATOR_OUT="$(cd "${MONITOR_DIR}" && uv run python -m homelab_monitor.kernel.watched_dirs "${PATHS[@]}")"; then
  echo "ERROR: watched-dirs validation failed; refusing to overwrite ${OUT}" >&2
  exit 1
fi
mapfile -t LINES <<< "${VALIDATOR_OUT}"
# `mapfile <<< ""` yields one empty element; collapse the all-empty case to 0.
if [[ ${#LINES[@]} -eq 1 && -z "${LINES[0]}" ]]; then
  LINES=()
fi

{
  echo "# auto-generated by scripts/generate-watched-dirs-mounts.sh — DO NOT EDIT"
  echo "# watched dirs: ${PATHS[*]}"
  echo "services:"
  echo "  monitor:"
  echo "    volumes:"
  if [[ ${#LINES[@]} -eq 0 ]]; then
    echo "      [] # no watched directories defined"
  else
    for line in "${LINES[@]}"; do
      echo "      - ${line}"
    done
  fi
} > "$OUT"

echo "Written: $OUT"
echo "Entries: ${#LINES[@]}"
